version: '3'

services:
  postgresdb:
    image: postgres:11.5
    environment:
      - POSTGRES_USER=library_store_api
      - POSTGRES_PASSWORD=library_store_api
      - POSTGRES_DB=library_store_api_development
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local